- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: pre-run | update package cache 
      tags: always
      pacman: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/user.yml
    - include: tasks/packages.yml
