---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories 
      tags: always
      pacman: update_cache= yes
      changed_when: False

  tasks:
    - include: tasks/user.yml
    - include: tasks/packages.yml
