-name: install dependencies 
  pacman: 
    name: Basic Pacmanstuff
      - networkmanager
      - network-manager-applet
      - sudo
      - doas
      - htop
      - xorg-server
      - xorg-xinit
      - xterm
      - awesome
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
      - vim
      - npm
      - python3
      - pyright
      - neovim
      - git
- name: git and shell stuff 
  shell: git clone --depth 1 https://github.com/wbthomason/packer.nvim\ ~/.local/share/nvim/site/pack/packer/start/packer.nvim
- name: enabling stuff 
  shell:
    echo "exec awesome" > ~/.xinitrc
    systemctl enable NetworkManager
    systemctl start NetworkManager  
  register: "output"
   
  
- debug: var=output.stdout_lines


